export { default as CategoryDialog } from './Category/index.vue'
export { default as ProductDialog } from './Product/index.vue'
export { default as AccountDialog } from './Account/index.vue'
export { default as ConfirmDialog } from './Confirm/index.vue'
export { default as CartAndOrderDialog } from './CartAndOrder/index.vue'